### ISSUE TITLE
double banner ad

### ISSUE THREAD

**Issue by EMI-INDO** [admob-plus/admob-plus#232]
load benner ad display banner, when i reload benner ad display banner, it happens double?

![Screenshot_2021-03-03-00-30-20-600](https://user-images.githubusercontent.com/78555833/109691067-a148c880-7bb9-11eb-80ab-e74b32f75946.jpg)

**Comment by ratson** [comment]
@EMI-INDO Android? How do you reload the banner?

**Comment by EMI-INDO** [comment]
**this is my code**


async Bannerload()
{
  await admob.start()
  const banner = new admob.BannerAd({
                adUnitId: 'ca-app-pub-3940256099942544/6300978111',
                position: 'top',                        
  })
  await banner.load()
}

////////////////////////////////

async BannerShow()
{
  await admob.start()
  const banner = new admob.BannerAd({
                adUnitId: 'ca-app-pub-3940256099942544/6300978111',
                position: 'top',                        
  })
  await banner.show()
}

**Comment by ratson** [comment]
@EMI-INDO I have just corrected a mistake in the docs, where there is no `banner.load()` method and you should get an error for doing so. Is that causing your problem?

**Comment by EMI-INDO** [comment]
@ratson I tried it without loading, still getting the same error
maybe this is an error in my own code, and I can't banner.hide () either

Thank you for your answers
