### ISSUE TITLE
Cocoapods cannot find a compatible version GoogleUserMessagingPlatform affecting AdMob

### ISSUE THREAD

**Issue by konguele** [admob-plus/admob-plus#625]
Good Morning,

I have created my game with Gdevelop, for Android it has worked perfectly, but on iOS I find this recurring error. I don't know what else to do and I'm desperate, because I can't find a solution. I don't know if it's a conflict between cordova-plugin-consent and admob-plus-cordova, but I keep getting this error and I don't know what to do.

```
Installing "admob-plus-cordova" for ios

[!] The `Jabali Espacial [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Jabali Espacial [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.release.xcconfig'. This can lead to problems with the CocoaPods installation
Adding admob-plus-cordova to package.json
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Failed to install 'cordova-plugin-consent': Error: Command failed with exit code 1: pod install --verbose
  Preparing

[!] CocoaPods could not find compatible versions for pod "GoogleUserMessagingPlatform":
  In snapshot (Podfile.lock):
    GoogleUserMessagingPlatform (= 2.1.0, >= 1.1)

  In Podfile:
    GoogleUserMessagingPlatform (~> 2.0.0)

Specs satisfying the `GoogleUserMessagingPlatform (~> 2.0.0), GoogleUserMessagingPlatform (= 2.1.0, >= 1.1)` dependency were found, but they required a higher minimum deployment target.

```

I add the complete log in case it can help.

Thanks for your help.
[log.txt](https://github.com/admob-plus/admob-plus/files/13038696/log.txt)

**Comment by sachithd** [comment]
Try the following steps.

1. Make sure the config.xml is correctly updated with
```
<preference name="deployment-target" value="12.0" />
<preference name="SwiftVersion" value="5.3" />
```
[https://admob-plus.github.io/docs/cordova/installation]

2. Remove the Podfile.lock in Platform -> ios 

3. run cd platforms/ios && pod install --repo-update

**Comment by EYALIN** [comment]
@konguele try using "community-admob-plus-cordova" instead.
it is forked from this repo, and all IOS issues are fixed there and it's up to date.
we will stay there until @ratson (which we highly appreciated) will come back to us

**Comment by konguele** [comment]
Hello @sachithd ,

I have tried your solution, but I get the following problem in Xcode:
<img width="1019" alt="Captura de pantalla 2023-10-23 a las 7 11 11" src="https://github.com/admob-plus/admob-plus/assets/64000046/501ee6c7-8f96-4687-9173-d11
<img width="473" alt="Captura de pantalla 2023-10-23 a las 7 11 56" src="https://github.com/admob-plus/admob-plus/assets/64000046/2500e9d1-d9a6-457a-b87f-670aab0cb91f">
c10613f71">

**Comment by konguele** [comment]
Hello @EYALIN ,

I have also tried the plugin you indicate, but it still doesn't work. I attach the complete log:

```
Discovered 
[log.txt](https://github.com/admob-plus/admob-plus/files/13066428/log.txt)
plugin "community-admob-plus-cordova". Adding it to the project
Installing "community-admob-plus-cordova" for ios
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--          0 7456k    0 25595    0     0  46358      0  0:02:44 --:--:--  0:02:44 4722   100 7456k  100 7456k    0     0  6475k      0  0:00:01  0:00:01 --:--:-- 6540k
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--         60 9347k   60 5695k    0     0  8703k      0  0:00:01 --:--:--  0:00:01 8829   100 9347k  100 9347k    0     0  9985k      0 --:--:-- --:--:-- --:--:--  9.8M
     Cloning into '/var/folders/3d/hb1kk27n6zx4ntzrr2lj8q9c0000gn/T/d20231023-3529-hjvxhc'...
     Note: switching to '819d0a2173aff699fb8c364b6fb906f7cdb1a692'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     

[!] The `Jabali Espacial [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Jabali Espacial [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Jabali Espacial/Pods-Jabali Espacial.release.xcconfig'. This can lead to problems with the CocoaPods installation
Adding community-admob-plus-cordova to package.json
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Failed to install 'cordova-plugin-consent': Error: Command failed with exit code 1: pod install --verbose
```

**Comment by sachithd** [comment]
> community-admob-plus-cordova

Try removing the plugin and adding it back. (or add the plugin after adding the platform ios)

**Comment by sachithd** [comment]
> Hello @sachithd ,
> 
> I have tried your solution, but I get the following problem in Xcode:
> 
> <img alt="Captura de pantalla 2023-10-23 a las 7 11 11" width="1019" src="https://user-images.githubusercontent.com/64000046/277238305-b246fe45-892b-44da-8346-4b5c1fa38525.png">
> Admob exists: <img alt="Captura de pantalla 2023-10-23 a las 7 11 56" width="473" src="https://user-images.githubusercontent.com/64000046/277238373-038f245d-ffe6-45fc-9014-8c8e7c71d42c.png">

Try removing the plugin and adding it back. (or add the plugin after adding the platform ios)
