### ISSUE TITLE
Can't hide banner after initialize it

### ISSUE THREAD

**Issue by boreales** [admob-plus/admob-plus#97]
### Is this a bug report?

Yes

### Environment

  AdMob Plus Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 181.52 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0_181 - /usr/bin/javac
    npmPackages:
      com-sarriaroman-photoviewer: ^1.2.0 => 1.2.1 
      cordova-admob-plus: 0.27.0 => 0.27.0 
      cordova-android: 7.1.4 => 7.1.4 
      cordova-android-support-gradle-release: ^2.0.1 => 2.0.1 
      cordova-ios: 4.5.5 => 4.5.5 
      cordova-plugin-advanced-http: ^2.0.4 => 2.0.6 
      cordova-plugin-android-permissions: ^1.0.0 => 1.0.0 
      cordova-plugin-camera: ^4.0.3 => 4.0.3 
      cordova-plugin-device: ^2.0.2 => 2.0.2 
      cordova-plugin-file: ^6.0.1 => 6.0.1 
      cordova-plugin-file-transfer: ^1.7.1 => 1.7.1 
      cordova-plugin-geolocation: ^4.0.1 => 4.0.1 
      cordova-plugin-headercolor: ^1.0.0 => 1.0.0 
      cordova-plugin-inappbrowser: ^3.0.0 => 3.0.0 
      cordova-plugin-ionic-keyboard: ^2.1.3 => 2.1.3 
      cordova-plugin-ionic-webview: ^3.1.2 => 3.1.2 
      cordova-plugin-mauron85-background-geolocation: ^3.0.0-alpha.50 => 3.0.0-alpha.50 
      cordova-plugin-nativestorage: ^2.3.2 => 2.3.2 
      cordova-plugin-request-location-accuracy: ^2.2.3 => 2.2.3 
      cordova-plugin-splashscreen: ^5.0.2 => 5.0.2 
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2 
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3 
      cordova-plugin-x-socialsharing: ^5.4.4 => 5.4.4 
      cordova-sqlite-storage: 2.3.1 => 2.3.1 
      cordova.plugins.diagnostic: ^4.0.11 => 4.0.12 
      uk.co.workingedge.phonegap.plugin.launchnavigator: ^4.2.2 => 4.2.2 
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 4.12.0

### Steps to Reproduce

(Write your steps here:)

1. Adding cordova plugin admob-plus
2. Show the admob banner
3. Trying to hide or remove the admob banner

### Expected Behavior

The banner should be hidden when the method hide is called.

### Actual Behavior

Nothing happens. Not any log and the banner is still visible after calling the hide method.

### Reproducible Demo

```
  if(platform.is('cordova')){
        admob.banner.show({
          id: {
              android: 'ca-app-pub-XXX/XXX',
              ios: 'ca-app-pub-XXX/XXX',
            },
          position: 'bottom',
          size:'FULL_BANNER'
        });
        admob.banner.hide();
      }
```

**Comment by nathantaal** [comment]
Look in your console and you should see the following error:

**Comment by lreiner** [comment]
```
    this.admob.banner.hide({
        android: '',
        ios: ''
      }
    )
```
this is the correct way to hide a banner. Hide function only allows AdUnitIdOption which looks like mentioned here: https://admob-plus.github.io/docs/ad-request-options.html

**Comment by Bktechmasala** [comment]
come to my channel and subscribe my channel watch my angular related video solved with perfect solutions.
https://www.youtube.com/watch?v=EPysW31oryk

**Comment by nathantaal** [comment]
> ```
>     this.admob.banner.hide({
>         android: '',
>         ios: ''
>       }
>     )
> ```
> 
> this is the correct way to hide a banner. Hide function only allows AdUnitIdOption which looks like mentioned here: https://admob-plus.github.io/docs/ad-request-options.html

I can confirm this being the correct way. Another issue that should be closed.

**Comment by fpassa** [comment]
Still not working for me under Ionic 4 Cordova 9 App.

I'm using the following code to show the banner and it's displayed without any issue.
  ```
this.admob.banner.show({
            id: this.adId,
            position: 'bottom',
            size: AdSizeType.SMART_BANNER
            })
            .then(() => console.log('Banner ad loaded'))
            .catch(err => console.error('Error loading banner ad:', err));             

```
But none of the previous indicated solutions hide the banner in my App.

I'm importing the following modules:
```
import { AdMob } from '@admob-plus/ionic';
import { AdSizeType } from '@admob-plus/core/dist/constants';
```
As any other module, like native 'ionic-admob'  doesn't compile or create errors in Ionic build process.

My environment is as follow:
```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/flavio/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 9 other plugins)

Utility:

   cordova-res : 0.2.0 (update available: 0.6.0)
   native-run  : 0.2.2 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/flavio/Library/android-sdk-macosx)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-libgoogleadmobads 7.13.1 "iOS Google AdMob Ads library"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-dbcopy 2.1.2 "sqlDB"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-payment-iap 2.0.52 "Cordova IAP plugin"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
```

**Comment by svzi** [comment]
@fpassa Did you find a solution?

**Comment by fpassa** [comment]
I switched to AdMob free

**Comment by svzi** [comment]
Ok, thanks for letting me know... Maybe I should consider that as well.

**Comment by nathantaal** [comment]
@fpassa @svzi 
I will try to explain it one more time using a full code example (my admobservice.ts)
At first, you should remove @admob-plus/ionic since that package is broken, just like ionic-native/admob-plus is broken.
You would only want one dependency in your package.json

```
"cordova-admob-plus": "^0.30.0"
```

Yes, this will be a cordova-only service (Which does work with Capacitor btw)

```
import {Injectable} from '@angular/core';

declare var admob;

@Injectable({
    providedIn: 'root'
})
export class AdmobService {

    private ads = true;

    constructor() {
    }

    getAdsEnabled() {
        return this.ads;
    }

    showBannerAd() {
        admob.banner.show({
            id: {
                android: 'ca-app-pub-xxx/xx'
            },
        });
    }

    disableAds() {

        admob.banner.hide({
            android: 'ca-app-pub-xxx/xx'
        });

        this.ads = false;
    }

    showFullscreenAd() {
        admob.interstitial.load({
            id: {
                android: 'ca-app-pub-xyz/xy'
            },
        }).then(() => admob.interstitial.show());
    }

    showVideoAd() {
        admob.rewardVideo.load({
            id: {
                android: 'ca-app-pub-abc/ab'
            },
        }).then(() => admob.rewardVideo.show());
    }
}
```

This works for me in production.

**Comment by fpassa** [comment]
Sorry, this is too late for me. I switched to Admob-free, followed the
instructions and just simple worked on the first attempt. If instructions
are not clear, sample code not provided or missing API documentation or
integration, it's hard to spend a week or more trying to figure out why is
not working as it should be.

May be, next time...may be next project.

Good luck

**Comment by svzi** [comment]
@nathantaal Thanks for the code, it's just not working on iOS. It's working fine on Android, but the same code (I even copied and pasted your code, and adapted only the ad ids) doesn't work on iOS. Banner showing works fine. When I call ```
admob.banner.hide({
      android: 'ca-app-pub-xxx/xx'
});
```
the iOS app gets a white screen and hangs... Nothing more, no error message in the console and nothing else. Really frustrating. This plugin is really painful to use, at least for me. I will probably follow in @fpassa footsteps and switch to a plugin that simple works. This should be no rocket since. I've spend so many hours on this topic, it's really more than frustrating, it's annoying.

**Comment by nathantaal** [comment]
@fpassa @svzi If on Cordova, sure, give admobfree a try. For capacitor you can also use capacitor-admob.

**Comment by svzi** [comment]
Awesome! I finally tried https://github.com/ratson/cordova-plugin-admob-free and it was running in minutes. Without any flaws! For anyone who has trouble with this plugin, I can strongly recommend to have a look at the old one (admob-free).

**Comment by kdk8747** [comment]
Any updates?
When I call the banner.hide() method with navCtrl.pop() to move to one of the tabs page, the iOS app gets a white screen and hangs. without any error message.
It's working fine on Android.

**Comment by kdk8747** [comment]
Now It's working perfectly. Thanks.

**Comment by berokapp** [comment]
I doe it like that and its working
function  hidbaner() {
admob.banner.hide({
android: 'ca-app-pub-3940256099942544/6300978111'
 });};
